### PR TITLE
Use a proper unit for upload/download speeds

### PR DESCRIPTION
**Pull request by TTtie**
Download/upload speeds are in megabits you knob

### CODE REVIEW

**Comment by TTtie** [comment]
@aerofusionyt review or riot

**Comment by StupidDan** [comment]
ur mum gay lol

**Comment by billyprice1** [comment]
no u

**Comment by StupidDan** [comment]
no u no returns

**Comment by TTtie** [comment]
>:(

**Comment by mrdnomaid** [comment]
Looks fine to me lol, although maybe `Mbps` would be more appropriate

**Pull request merged**
